'use strict';

// Every user-facing text, shared by the main process (tray, menus) and all windows.
// Both languages must have exactly the same keys – test/i18n.test.mjs checks that.
// {name} placeholders are filled in by t(); keys ending in _one / _other are plural forms.

const de = {
  // status
  'status.focus': 'Fokus',
  'status.soon': 'Gleich Pause',
  'status.break': 'Pause',
  'status.paused': 'Pausiert',
  'status.away': 'Abwesend',

  // window bar & rail
  'bar.home': 'Atem, nach oben',
  'bar.saved': 'Gespeichert',
  'bar.minimize': 'Minimieren',
  'bar.maximize': 'Maximieren',
  'bar.close': 'Schliessen',
  'bar.theme': 'Hell oder dunkel',
  'bar.language': 'Sprache',
  'rail.label': 'Abschnitte',
  'rail.hero': 'Jetzt',
  'rail.rhythm': 'Rhythmus',
  'rail.eyes': 'Augen',
  'rail.program': 'Programm',
  'rail.strict': 'Konsequenz',
  'rail.stats': 'Bilanz',
  'rail.system': 'Feinschliff',
  'ui.less': 'Weniger',
  'ui.more': 'Mehr',

  // hero
  'hero.kicker': 'Dein Pausen-Begleiter',
  'hero.line1': 'Atem',
  'hero.line2': 'holen.',
  'hero.next': 'Nächste Pause in',
  'hero.pausedUntil': 'Pausiert bis',
  'hero.breakRunning': 'Pause läuft',
  'hero.microRunning': 'Mikropause',
  'hero.away': 'Du bist gerade weg',
  'hero.fresh': 'Frisch im Fokus',
  'hero.focusedFor': 'Seit {time} im Fokus',
  'hero.microIn': 'Mikropause in {time}',
  'hero.pausedLeft': 'Noch {time}. Atem wartet still.',
  'hero.breakSub': 'Schön, dass du sie machst.',
  'hero.awaySub': 'Die Uhr steht still, bis du zurück bist.',
  'hero.breakNow': 'Jetzt Pause machen',
  'hero.resume': 'Fortsetzen',
  'hero.breakBusy': 'Pause läuft',
  'hero.pause': 'Pausieren',
  'hero.p30': '30 Min.',
  'hero.p60': '1 Std.',
  'hero.p120': '2 Std.',
  'hero.tomorrow': 'Bis morgen',
  'hero.scroll': 'Scrollen',
  marquee: 'Einatmen <em>✳</em> Ausatmen <em>✳</em> Innehalten <em>✳</em> Weitermachen <em>✳</em> ',

  // rhythm
  'rhythm.label': 'Rhythmus',
  'rhythm.title': 'Arbeite im <em>Takt,</em> nicht im Tunnel.',
  'rhythm.lead': 'Wie lange tauchst du ab, wie lange tauchst du auf? Stell es ein, Atem erinnert dich daran. Sanft, aber bestimmt.',
  'rhythm.pomodoro': 'Pomodoro',
  'rhythm.classic': 'Klassisch',
  'rhythm.deep': 'Tiefenarbeit',
  'rhythm.focus': 'Fokus',
  'rhythm.break': 'Pause',
  'rhythm.focusAria': 'Fokuszeit in Minuten',
  'rhythm.breakAria': 'Pausenlänge in Minuten',
  'rhythm.legendFocus': 'Fokus',
  'rhythm.legendBreak': 'Pause',
  'rhythm.legendMicro': 'Mikropausen',
  'rhythm.legendCycle': 'Min. pro Zyklus',
  'rhythm.insight': 'An einem 8‑Stunden‑Tag sind das <b>{breaks}</b> und <b>{minutes} Minuten</b> nur für dich',
  'rhythm.insightMicro': ', dazu <b>{micro} Mikropausen</b> für die Augen.',
  'rhythm.insightEnd': '.',
  'n.breaks_one': '{n} Pause',
  'n.breaks_other': '{n} Pausen',

  // eyes
  'eyes.label': 'Augen',
  'eyes.ruleAria': 'Die 20-20-20-Regel',
  'eyes.every': 'alle {n} Min.',
  'eyes.lookUp': 'kurz unterbrechen',
  'eyes.seconds': '{n} Sekunden',
  'eyes.long': 'lang',
  'eyes.distance': '6 Meter',
  'eyes.far': 'weit schauen',
  'eyes.lead': 'Stundenlang auf den Bildschirm zu fokussieren, verkrampft den Ziliarmuskel. Ein kurzer Blick in die Ferne entspannt ihn und beugt müden, trockenen Augen vor.',
  'eyes.micro': 'Mikropausen',
  'eyes.microDesc': 'Kleine Augen-Pausen zwischen den grossen.',
  'eyes.interval': 'Rhythmus',
  'eyes.duration': 'Dauer',
  'eyes.style': 'Darstellung',
  'eyes.styleDesc': 'Dezente Kapsel oben oder ganzer Bildschirm.',
  'eyes.capsule': 'Kapsel',
  'eyes.fullscreen': 'Vollbild',
  'eyes.sec': '{n} Sek.',

  // program
  'program.label': 'Pausenprogramm',
  'program.title': 'Was deine Pause <em>füllt.</em>',
  'program.lead': 'Aus deinen Übungen entsteht ein geführtes Programm, das genau in deine Pausenlänge passt.',
  'program.breath': 'Atmung',
  'program.breathDesc': 'Ein ruhiger Atemrhythmus, der dein Nervensystem herunterfährt.',
  'program.eyes': 'Augen',
  'program.eyesDesc': 'Fernblick, Augenkreisen, Palming und bewusstes Blinzeln.',
  'program.stretch': 'Dehnen',
  'program.stretchDesc': 'Nacken, Schultern und Rücken lockern, die vom Sitzen fest sind.',
  'program.move': 'Bewegen',
  'program.moveDesc': 'Aufstehen, ein Glas Wasser holen, ein paar Schritte gehen.',
  'program.inProgram': '{name} im Programm',
  'program.calm': 'Ruhig 4·6',
  'program.box': 'Box 4·4·4·4',
  'program.478': '4·7·8',
  'program.ready': 'Bereit?',
  'program.ctaTitle': 'Spür, wie sich eine <em>Pause</em> anfühlt.',
  'program.try': 'Pause testen',
  'program.tryMicro': 'Mikropause testen',
  'visual.in': 'ein',
  'visual.hold': 'halten',
  'visual.out': 'aus',

  // strictness
  'strict.label': 'Konsequenz',
  'strict.title': 'Wie <em>streng</em> darf ich sein?',
  'strict.gentle': 'Sanft',
  'strict.balanced': 'Ausgewogen',
  'strict.strict': 'Strikt',
  'strict.fact.skip': 'Überspringen',
  'strict.fact.snooze': 'Verschieben',
  'strict.fact.esc': 'Esc-Taste',
  'strict.fact.emergency': 'Notausstieg',
  'strict.gentle.quote': 'Ich erinnere dich. <em>Du</em> entscheidest.',
  'strict.gentle.skip': 'ein Klick',
  'strict.gentle.snooze': 'so oft du willst',
  'strict.gentle.esc': 'beendet die Pause',
  'strict.gentle.button': 'Überspringen',
  'strict.gentle.hint': 'Ein Klick genügt.',
  'strict.balanced.quote': 'Gerade genug Reibung, damit du nicht <em>aus Reflex</em> wegklickst.',
  'strict.balanced.skip': 'kurz gedrückt halten',
  'strict.balanced.snooze': 'höchstens 2×',
  'strict.balanced.esc': 'wirkungslos',
  'strict.balanced.button': 'Zum Überspringen halten',
  'strict.balanced.hint': 'Halte gedrückt, bis sich der Knopf füllt.',
  'strict.strict.quote': 'Für Tage, an denen du dich <em>selbst</em> nicht bremsen kannst.',
  'strict.strict.skip': 'nicht vorgesehen',
  'strict.strict.snooze': 'genau einmal',
  'strict.strict.emergency': '5 Sekunden halten',
  'strict.strict.button': 'Notausstieg · 5 s halten',
  'strict.strict.hint': 'Nur für echte Notfälle.',
  'strict.try': 'Probier es aus',
  'strict.skipped': 'Übersprungen ✓',
  'strict.skippedHint': 'Genau so. Im Ernstfall geht es zurück an die Arbeit.',
  'strict.warn': 'Vorwarnung',
  'strict.warnDesc': 'Kündigt die Pause vorher an, damit du fertig denken kannst.',
  'strict.lead': 'Vorlauf',
  'strict.snoozeBy': 'Verschieben um',
  'strict.snoozeByDesc': 'Wenn es gerade wirklich nicht passt.',
  'strict.min': '{n} Min.',

  // stats
  'stats.label': 'Bilanz',
  'stats.title': '<em>Heute.</em>',
  'stats.none': 'Noch keine Pause heute. Die erste kommt bestimmt.',
  'stats.summary': '{taken} von {due} Pausen genommen.',
  'stats.great': 'Stark.',
  'stats.good': 'Da geht noch was.',
  'stats.meh': 'Morgen wird ruhiger.',
  'stats.taken': 'Pausen eingehalten',
  'stats.active': 'Aktive Zeit',
  'stats.micro': 'Mikropausen',
  'stats.streak': 'Serie',
  'stats.day_one': 'Tag',
  'stats.day_other': 'Tage',
  'stats.week': 'Letzte 7 Tage',
  'stats.legendBreaks': 'Pausen',
  'stats.legendSkipped': 'übersprungen',

  // system
  'system.label': 'Feinschliff',
  'system.title': 'Die <em>Details.</em>',
  'system.appearance': 'Erscheinungsbild',
  'system.appearanceDesc': 'Dunkel, hell oder passend zu deinem System.',
  'system.language': 'Sprache',
  'system.languageDesc': 'Oder die Sprache deines Systems.',
  'theme.dark': 'Dunkel',
  'theme.light': 'Hell',
  'theme.system': 'System',
  'lang.system': 'System',
  'system.autostart': 'Mit dem System starten',
  'system.autostartDesc': 'Atem startet still im Hintergrund, sobald du dich anmeldest.',
  'system.autostartDev': 'Wird aktiv, sobald Atem installiert ist (Entwicklungsmodus).',
  'system.idle': 'Abwesenheit erkennen',
  'system.idleDesc': 'Bist du länger weg, zählt das als Pause und der Zähler beginnt neu.',
  'system.idleAfter': 'Als abwesend gilt ab',
  'system.chime': 'Klangschale',
  'system.chimeDesc': 'Ein leiser Ton zu Beginn und am Ende jeder Pause.',
  'system.ocean': 'Meeresrauschen',
  'system.oceanDesc': 'Wellen, die mit deinem Atem kommen und gehen.',
  'system.volume': 'Lautstärke',
  'system.trayCountdown': 'Countdown in der Menüleiste',
  'system.trayCountdownDesc': 'Die Minuten bis zur Pause direkt neben dem Symbol.',
  'system.mood': 'Stimmung',
  'palette.salbei': 'Salbei',
  'palette.daemmerung': 'Dämmerung',
  'palette.gletscher': 'Gletscher',
  'palette.glut': 'Glut',
  'outro.title': 'Atme. <em>Dann weiter.</em>',
  'outro.version': 'Atem {v} · Mit Ruhe gebaut',
  'outro.quit': 'Atem beenden',
  'outro.quitConfirm': 'Wirklich beenden? Nochmals klicken',
  'cursor.drag': 'Ziehen',
  'cursor.blink': 'Blinzeln',

  // popover
  'pop.untilNext': 'bis zur nächsten Pause',
  'pop.pausedUntil': 'pausiert bis {time}',
  'pop.microRunning': 'Mikropause läuft',
  'pop.breakRunning': 'Pause läuft',
  'pop.away': 'Du bist gerade weg. Die Uhr steht still.',
  'pop.microIn': 'Mikropause in {time}',
  'pop.sec': 'Sek.',
  'pop.minute_one': 'Minute',
  'pop.minute_other': 'Minuten',
  'pop.hours': 'Stunden',
  'pop.pause': 'Pausieren',
  'pop.p30': '30 Min.',
  'pop.p60': '1 Std.',
  'pop.p120': '2 Std.',
  'pop.tomorrow': 'Morgen',
  'pop.today_one': 'Heute <b>{n}</b> Pause · <b>{focus}</b> Fokus',
  'pop.today_other': 'Heute <b>{n}</b> Pausen · <b>{focus}</b> Fokus',
  'pop.settings': 'Einstellungen',
  'pop.quit': 'Beenden',
  'pop.sure': 'Sicher?',

  // island
  'island.warn.title': 'Gleich ist Pause',
  'island.warn.sub': 'in <b>{time}</b> · bring den Gedanken zu Ende',
  'island.now': 'Jetzt',
  'island.plus': '+{n} Min.',
  'island.micro.title': 'Blick in die Ferne',
  'island.micro.sub': 'noch <b>{time}</b> · such dir einen Punkt weit weg',
  'island.sec': '{n} Sek.',
  'island.skip': 'Überspringen',
  'island.microDone.title': 'Danke.',
  'island.microDone.sub': 'Deine Augen auch.',
  'island.hello.title': 'Atem ist da',
  'island.nextAt': 'Nächste Pause um <b>{time}</b>',
  'island.settings': 'Einstellungen',
  'island.welcome.title': 'Willkommen zurück',
  'island.welcome.sub': 'Deine Abwesenheit zählt als Pause.',
  'island.paused.title': 'Erinnerungen pausiert',
  'island.paused.sub': 'bis <b>{time}</b>',
  'island.resume': 'Fortsetzen',
  'island.resumed.title': 'Weiter geht’s',
  'island.hint.title': 'Ich bleibe im Hintergrund',
  'island.hint.mac': 'Du findest mich oben rechts in der <b>Menüleiste</b>.',
  'island.hint.win': 'Unten rechts in der <b>Taskleiste</b>, eventuell unter <b>^</b>.',

  // break overlay
  'break.kind.long': 'Pause',
  'break.kind.micro': 'Mikropause',
  'break.kind.preview': 'Vorschau',
  'break.done': 'fertig',
  'phase.in': 'Einatmen',
  'phase.hold': 'Halten',
  'phase.out': 'Ausatmen',
  'phase.rest': 'Halten',
  'phase.eyesOpen': 'Augen auf',
  'group.breath': 'Atmung',
  'group.eyes': 'Augen',
  'group.stretch': 'Dehnen',
  'group.move': 'Bewegen',
  'breath.calm': 'Ruhiger Atem',
  'breath.box': 'Box-Atmung',
  'breath.478': '4-7-8-Atmung',
  'step.intro.title': 'Zeit für eine Pause.',
  'step.intro.text': 'Nimm die Hände von der Tastatur und lehn dich zurück.',
  'step.breath.text': 'Folge dem Licht. Durch die Nase ein, langsam durch den Mund wieder aus.',
  'step.far.title': 'Schau in die Ferne.',
  'step.far.text': 'Such dir einen Punkt, der mindestens sechs Meter weit weg ist. Am besten draussen.',
  'step.track.title': 'Folge dem Licht.',
  'step.track.text': 'Nur mit den Augen. Der Kopf bleibt ganz ruhig.',
  'step.palming.title': 'Augen zu.',
  'step.palming.text': 'Reibe die Handflächen warm und lege sie sanft über die geschlossenen Augen.',
  'step.palming.end': 'Öffne langsam die Augen und blinzle ein paar Mal.',
  'step.blink.title': 'Blinzeln.',
  'step.blink.text': 'Locker und bewusst. Das befeuchtet die Augen wieder.',
  'step.shoulders.title': 'Schultern kreisen.',
  'step.shoulders.text': 'Gross und langsam nach hinten. Atme dabei ruhig weiter.',
  'step.neck.title': 'Nacken dehnen.',
  'step.neck.text': 'Neige den Kopf sanft zur linken Schulter und halte.',
  'step.neck.switch': 'Und jetzt sanft zur rechten Schulter.',
  'step.reach.title': 'Streck dich.',
  'step.reach.text': 'Steh auf, Arme nach oben und ganz lang werden.',
  'step.move.title': 'Beweg dich.',
  'step.move.text': 'Hol dir ein Glas Wasser, geh ein paar Schritte, schau aus dem Fenster.',
  'step.micro.title': 'Blick in die Ferne.',
  'step.micro.text': 'Such dir einen Punkt weit weg und lass die Augen dort ruhen.',
  'break.skip': 'Überspringen',
  'break.hold': 'Zum Überspringen halten',
  'break.emergency': 'Notausstieg · 5 s halten',
  'break.endPreview': 'Vorschau beenden',
  'break.later': '{n} Min. später',
  'break.left': 'noch {n}×',
  'break.finished': 'Pause beendet',
  'break.doneTitle': 'Schön <em>gemacht.</em>',
  'break.doneNth': 'Das war deine {nth} Pause heute. Dein Kopf dankt es dir.',
  'break.doneGeneric': 'Dein Kopf dankt es dir.',
  'break.donePreview': 'So fühlt sich eine Pause mit Atem an.',
  'break.back': 'Zurück an die Arbeit',
  'break.enter': 'Enter ↵',
  'break.thanks': 'Danke.',
  'break.onward': 'Weiter geht es.',

  // tray & menus (main process)
  'tray.micro': 'Mikropause',
  'tray.break': 'Pause läuft',
  'tray.paused': 'pausiert bis {time}',
  'tray.away': 'du bist gerade weg',
  'tray.next': 'nächste Pause in {dur}',
  'menu.breakNow': 'Jetzt Pause machen',
  'menu.microNow': 'Mikropause jetzt',
  'menu.resume': 'Erinnerungen fortsetzen',
  'menu.pause': 'Erinnerungen pausieren',
  'menu.p30': '30 Minuten',
  'menu.p60': '1 Stunde',
  'menu.p120': '2 Stunden',
  'menu.tomorrow': 'Bis morgen früh',
  'menu.settings': 'Einstellungen …',
  'menu.quit': 'Atem beenden',
  'menu.about': 'Über Atem',
  'menu.hide': 'Atem ausblenden',
  'menu.edit': 'Bearbeiten',
  'menu.copy': 'Kopieren',
  'menu.selectAll': 'Alles auswählen',
  'menu.window': 'Fenster',
  'menu.minimize': 'Minimieren',
  'menu.close': 'Schliessen',
};

const en = {
  // status
  'status.focus': 'Focus',
  'status.soon': 'Break soon',
  'status.break': 'Break',
  'status.paused': 'Paused',
  'status.away': 'Away',

  // window bar & rail
  'bar.home': 'Atem, back to top',
  'bar.saved': 'Saved',
  'bar.minimize': 'Minimize',
  'bar.maximize': 'Maximize',
  'bar.close': 'Close',
  'bar.theme': 'Light or dark',
  'bar.language': 'Language',
  'rail.label': 'Sections',
  'rail.hero': 'Now',
  'rail.rhythm': 'Rhythm',
  'rail.eyes': 'Eyes',
  'rail.program': 'Program',
  'rail.strict': 'Firmness',
  'rail.stats': 'Summary',
  'rail.system': 'Details',
  'ui.less': 'Less',
  'ui.more': 'More',

  // hero
  'hero.kicker': 'Your break companion',
  'hero.line1': 'Take a',
  'hero.line2': 'breath.',
  'hero.next': 'Next break in',
  'hero.pausedUntil': 'Paused until',
  'hero.breakRunning': 'Break in progress',
  'hero.microRunning': 'Micro break',
  'hero.away': 'You’re away right now',
  'hero.fresh': 'Freshly focused',
  'hero.focusedFor': 'Focused for {time}',
  'hero.microIn': 'Micro break in {time}',
  'hero.pausedLeft': '{time} to go. Atem is waiting quietly.',
  'hero.breakSub': 'Good on you for taking it.',
  'hero.awaySub': 'The clock stands still until you’re back.',
  'hero.breakNow': 'Take a break now',
  'hero.resume': 'Resume',
  'hero.breakBusy': 'Break in progress',
  'hero.pause': 'Pause reminders',
  'hero.p30': '30 min',
  'hero.p60': '1 hour',
  'hero.p120': '2 hours',
  'hero.tomorrow': 'Until tomorrow',
  'hero.scroll': 'Scroll',
  marquee: 'Breathe in <em>✳</em> Breathe out <em>✳</em> Pause <em>✳</em> Carry on <em>✳</em> ',

  // rhythm
  'rhythm.label': 'Rhythm',
  'rhythm.title': 'Work in <em>rhythm,</em> not in a tunnel.',
  'rhythm.lead': 'How long do you dive in, and how long do you come up for air? Set it once and Atem will remind you. Gently, but firmly.',
  'rhythm.pomodoro': 'Pomodoro',
  'rhythm.classic': 'Classic',
  'rhythm.deep': 'Deep work',
  'rhythm.focus': 'Focus',
  'rhythm.break': 'Break',
  'rhythm.focusAria': 'Focus time in minutes',
  'rhythm.breakAria': 'Break length in minutes',
  'rhythm.legendFocus': 'focus',
  'rhythm.legendBreak': 'break',
  'rhythm.legendMicro': 'micro breaks',
  'rhythm.legendCycle': 'min per cycle',
  'rhythm.insight': 'In an 8‑hour day that’s <b>{breaks}</b> and <b>{minutes} minutes</b> just for you',
  'rhythm.insightMicro': ', plus <b>{micro} micro breaks</b> for your eyes.',
  'rhythm.insightEnd': '.',
  'n.breaks_one': '{n} break',
  'n.breaks_other': '{n} breaks',

  // eyes
  'eyes.label': 'Eyes',
  'eyes.ruleAria': 'The 20-20-20 rule',
  'eyes.every': 'every {n} min',
  'eyes.lookUp': 'look up briefly',
  'eyes.seconds': '{n} seconds',
  'eyes.long': 'long',
  'eyes.distance': '20 feet',
  'eyes.far': 'into the distance',
  'eyes.lead': 'Hours of focusing on a screen tense up the ciliary muscle. A short look into the distance relaxes it and helps prevent tired, dry eyes.',
  'eyes.micro': 'Micro breaks',
  'eyes.microDesc': 'Small eye breaks between the big ones.',
  'eyes.interval': 'Interval',
  'eyes.duration': 'Duration',
  'eyes.style': 'Style',
  'eyes.styleDesc': 'A subtle capsule at the top, or the full screen.',
  'eyes.capsule': 'Capsule',
  'eyes.fullscreen': 'Full screen',
  'eyes.sec': '{n} sec',

  // program
  'program.label': 'Break program',
  'program.title': 'What fills your <em>break.</em>',
  'program.lead': 'Your exercises become a guided program that fits your break length exactly.',
  'program.breath': 'Breathing',
  'program.breathDesc': 'A calm breathing rhythm that winds your nervous system down.',
  'program.eyes': 'Eyes',
  'program.eyesDesc': 'Distance gazing, eye circles, palming and mindful blinking.',
  'program.stretch': 'Stretch',
  'program.stretchDesc': 'Loosen the neck, shoulders and back that sitting has stiffened.',
  'program.move': 'Move',
  'program.moveDesc': 'Stand up, get a glass of water, walk a few steps.',
  'program.inProgram': '{name} in the program',
  'program.calm': 'Calm 4·6',
  'program.box': 'Box 4·4·4·4',
  'program.478': '4·7·8',
  'program.ready': 'Ready?',
  'program.ctaTitle': 'Feel what a <em>break</em> feels like.',
  'program.try': 'Try a break',
  'program.tryMicro': 'Try a micro break',
  'visual.in': 'in',
  'visual.hold': 'hold',
  'visual.out': 'out',

  // strictness
  'strict.label': 'Firmness',
  'strict.title': 'How <em>strict</em> should I be?',
  'strict.gentle': 'Gentle',
  'strict.balanced': 'Balanced',
  'strict.strict': 'Strict',
  'strict.fact.skip': 'Skipping',
  'strict.fact.snooze': 'Snoozing',
  'strict.fact.esc': 'Esc key',
  'strict.fact.emergency': 'Emergency exit',
  'strict.gentle.quote': 'I remind you. <em>You</em> decide.',
  'strict.gentle.skip': 'one click',
  'strict.gentle.snooze': 'as often as you like',
  'strict.gentle.esc': 'ends the break',
  'strict.gentle.button': 'Skip',
  'strict.gentle.hint': 'One click is enough.',
  'strict.balanced.quote': 'Just enough friction that you don’t click it away <em>on reflex.</em>',
  'strict.balanced.skip': 'press and hold',
  'strict.balanced.snooze': 'twice at most',
  'strict.balanced.esc': 'does nothing',
  'strict.balanced.button': 'Hold to skip',
  'strict.balanced.hint': 'Keep holding until the button fills up.',
  'strict.strict.quote': 'For days when you can’t stop <em>yourself.</em>',
  'strict.strict.skip': 'not an option',
  'strict.strict.snooze': 'exactly once',
  'strict.strict.emergency': 'hold for 5 seconds',
  'strict.strict.button': 'Emergency exit · hold 5 s',
  'strict.strict.hint': 'For real emergencies only.',
  'strict.try': 'Try it',
  'strict.skipped': 'Skipped ✓',
  'strict.skippedHint': 'Exactly. In real life, this sends you back to work.',
  'strict.warn': 'Heads-up',
  'strict.warnDesc': 'Announces the break ahead of time so you can finish your thought.',
  'strict.lead': 'Lead time',
  'strict.snoozeBy': 'Snooze by',
  'strict.snoozeByDesc': 'For when it really doesn’t fit right now.',
  'strict.min': '{n} min',

  // stats
  'stats.label': 'Summary',
  'stats.title': '<em>Today.</em>',
  'stats.none': 'No breaks yet today. The first one is on its way.',
  'stats.summary': '{taken} of {due} breaks taken.',
  'stats.great': 'Excellent.',
  'stats.good': 'There’s room for more.',
  'stats.meh': 'Tomorrow will be calmer.',
  'stats.taken': 'Breaks taken',
  'stats.active': 'Active time',
  'stats.micro': 'Micro breaks',
  'stats.streak': 'Streak',
  'stats.day_one': 'day',
  'stats.day_other': 'days',
  'stats.week': 'Last 7 days',
  'stats.legendBreaks': 'Breaks',
  'stats.legendSkipped': 'skipped',

  // system
  'system.label': 'Details',
  'system.title': 'The <em>details.</em>',
  'system.appearance': 'Appearance',
  'system.appearanceDesc': 'Dark, light, or matching your system.',
  'system.language': 'Language',
  'system.languageDesc': 'Or whatever your system speaks.',
  'theme.dark': 'Dark',
  'theme.light': 'Light',
  'theme.system': 'System',
  'lang.system': 'System',
  'system.autostart': 'Start with your computer',
  'system.autostartDesc': 'Atem starts quietly in the background when you sign in.',
  'system.autostartDev': 'Takes effect once Atem is installed (development mode).',
  'system.idle': 'Detect time away',
  'system.idleDesc': 'If you’re away for a while, it counts as a break and the timer starts over.',
  'system.idleAfter': 'Count as away after',
  'system.chime': 'Singing bowl',
  'system.chimeDesc': 'A soft tone at the start and end of every break.',
  'system.ocean': 'Ocean sound',
  'system.oceanDesc': 'Waves that come and go with your breath.',
  'system.volume': 'Volume',
  'system.trayCountdown': 'Countdown in the menu bar',
  'system.trayCountdownDesc': 'Minutes until your break, right next to the icon.',
  'system.mood': 'Mood',
  'palette.salbei': 'Sage',
  'palette.daemmerung': 'Dusk',
  'palette.gletscher': 'Glacier',
  'palette.glut': 'Ember',
  'outro.title': 'Breathe. <em>Then carry on.</em>',
  'outro.version': 'Atem {v} · Built with calm',
  'outro.quit': 'Quit Atem',
  'outro.quitConfirm': 'Really quit? Click again',
  'cursor.drag': 'Drag',
  'cursor.blink': 'Blink',

  // popover
  'pop.untilNext': 'until your next break',
  'pop.pausedUntil': 'paused until {time}',
  'pop.microRunning': 'Micro break in progress',
  'pop.breakRunning': 'Break in progress',
  'pop.away': 'You’re away. The clock stands still.',
  'pop.microIn': 'Micro break in {time}',
  'pop.sec': 'sec',
  'pop.minute_one': 'minute',
  'pop.minute_other': 'minutes',
  'pop.hours': 'hours',
  'pop.pause': 'Pause reminders',
  'pop.p30': '30 min',
  'pop.p60': '1 hr',
  'pop.p120': '2 hrs',
  'pop.tomorrow': 'Tomorrow',
  'pop.today_one': 'Today <b>{n}</b> break · <b>{focus}</b> focus',
  'pop.today_other': 'Today <b>{n}</b> breaks · <b>{focus}</b> focus',
  'pop.settings': 'Settings',
  'pop.quit': 'Quit',
  'pop.sure': 'Sure?',

  // island
  'island.warn.title': 'Break coming up',
  'island.warn.sub': 'in <b>{time}</b> · finish your thought',
  'island.now': 'Now',
  'island.plus': '+{n} min',
  'island.micro.title': 'Look into the distance',
  'island.micro.sub': '<b>{time}</b> left · find a point far away',
  'island.sec': '{n} sec',
  'island.skip': 'Skip',
  'island.microDone.title': 'Thank you.',
  'island.microDone.sub': 'Your eyes say thanks, too.',
  'island.hello.title': 'Atem is here',
  'island.nextAt': 'Next break at <b>{time}</b>',
  'island.settings': 'Settings',
  'island.welcome.title': 'Welcome back',
  'island.welcome.sub': 'Your time away counts as a break.',
  'island.paused.title': 'Reminders paused',
  'island.paused.sub': 'until <b>{time}</b>',
  'island.resume': 'Resume',
  'island.resumed.title': 'Back at it',
  'island.hint.title': 'I’ll stay in the background',
  'island.hint.mac': 'You’ll find me in the <b>menu bar</b>, top right.',
  'island.hint.win': 'Bottom right in the <b>taskbar</b>, possibly under <b>^</b>.',

  // break overlay
  'break.kind.long': 'Break',
  'break.kind.micro': 'Micro break',
  'break.kind.preview': 'Preview',
  'break.done': 'done',
  'phase.in': 'Breathe in',
  'phase.hold': 'Hold',
  'phase.out': 'Breathe out',
  'phase.rest': 'Hold',
  'phase.eyesOpen': 'Eyes open',
  'group.breath': 'Breathing',
  'group.eyes': 'Eyes',
  'group.stretch': 'Stretch',
  'group.move': 'Move',
  'breath.calm': 'Calm breathing',
  'breath.box': 'Box breathing',
  'breath.478': '4-7-8 breathing',
  'step.intro.title': 'Time for a break.',
  'step.intro.text': 'Take your hands off the keyboard and lean back.',
  'step.breath.text': 'Follow the light. In through your nose, slowly out through your mouth.',
  'step.far.title': 'Look into the distance.',
  'step.far.text': 'Find a point at least twenty feet away. Outside, if you can.',
  'step.track.title': 'Follow the light.',
  'step.track.text': 'With your eyes only. Keep your head completely still.',
  'step.palming.title': 'Close your eyes.',
  'step.palming.text': 'Rub your palms warm and rest them gently over your closed eyes.',
  'step.palming.end': 'Slowly open your eyes and blink a few times.',
  'step.blink.title': 'Blink.',
  'step.blink.text': 'Easy and deliberate. It moistens your eyes again.',
  'step.shoulders.title': 'Roll your shoulders.',
  'step.shoulders.text': 'Big, slow circles backwards. Keep breathing calmly.',
  'step.neck.title': 'Stretch your neck.',
  'step.neck.text': 'Gently tilt your head towards your left shoulder and hold.',
  'step.neck.switch': 'Now gently towards your right shoulder.',
  'step.reach.title': 'Stretch up.',
  'step.reach.text': 'Stand up, arms overhead, and grow tall.',
  'step.move.title': 'Move a little.',
  'step.move.text': 'Get a glass of water, walk a few steps, look out of the window.',
  'step.micro.title': 'Look into the distance.',
  'step.micro.text': 'Find a point far away and let your eyes rest there.',
  'break.skip': 'Skip',
  'break.hold': 'Hold to skip',
  'break.emergency': 'Emergency exit · hold 5 s',
  'break.endPreview': 'End preview',
  'break.later': '{n} min later',
  'break.left': '{n}× left',
  'break.finished': 'Break complete',
  'break.doneTitle': 'Nicely <em>done.</em>',
  'break.doneNth': 'That was your {nth} break today. Your mind will thank you.',
  'break.doneGeneric': 'Your mind will thank you.',
  'break.donePreview': 'This is what a break with Atem feels like.',
  'break.back': 'Back to work',
  'break.enter': 'Enter ↵',
  'break.thanks': 'Thank you.',
  'break.onward': 'Back to it.',

  // tray & menus (main process)
  'tray.micro': 'Micro break',
  'tray.break': 'Break in progress',
  'tray.paused': 'paused until {time}',
  'tray.away': 'you’re away',
  'tray.next': 'next break in {dur}',
  'menu.breakNow': 'Take a break now',
  'menu.microNow': 'Micro break now',
  'menu.resume': 'Resume reminders',
  'menu.pause': 'Pause reminders',
  'menu.p30': '30 minutes',
  'menu.p60': '1 hour',
  'menu.p120': '2 hours',
  'menu.tomorrow': 'Until tomorrow morning',
  'menu.settings': 'Settings…',
  'menu.quit': 'Quit Atem',
  'menu.about': 'About Atem',
  'menu.hide': 'Hide Atem',
  'menu.edit': 'Edit',
  'menu.copy': 'Copy',
  'menu.selectAll': 'Select All',
  'menu.window': 'Window',
  'menu.minimize': 'Minimize',
  'menu.close': 'Close',
};

module.exports = { de, en };
